// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/erp-clarity/Dashboard.tsx": () => import("../components/mockups/erp-clarity/Dashboard.tsx"),
  "./components/mockups/erp-deep/Dashboard.tsx": () => import("../components/mockups/erp-deep/Dashboard.tsx"),
  "./components/mockups/erp-premium/Dashboard.tsx": () => import("../components/mockups/erp-premium/Dashboard.tsx"),
  "./components/mockups/erp-redesign/Dashboard.tsx": () => import("../components/mockups/erp-redesign/Dashboard.tsx"),
  "./components/mockups/erp-redesign/ListView.tsx": () => import("../components/mockups/erp-redesign/ListView.tsx"),
  "./components/mockups/erp-redesign/ThemeSettings.tsx": () => import("../components/mockups/erp-redesign/ThemeSettings.tsx")
};
